### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [ayerdines/nimble-scraper#5]
Hello Dinesh 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

**Comment by ayerdines** [comment]
Sure, thank you!!

**Comment by ayerdines** [comment]
Should I add you as a collaborator to the repo, so that you can review the PRs?

**Comment by olivierobert** [comment]
I provided feedback on the opened PRs. Thank you for the fixes. 

As you provided feedback on all open issues, that is sufficient for us to wrap up this application stage. Indeed, we aim to emulate the code review process and do not expect to have fixes for everything to keep the code review process short. I will provide my assessment to Tra who will update you on your application status.

**Comment by ayerdines** [comment]
Thank you @olivierobert for the suggestions. Learned a lot during this process.
